### ISSUE TITLE
Detail in the paper

### ISSUE THREAD

**Issue by liuyishoua** [OpenGSL/OpenGSL#22]
l noticed that the highlight color in Table. 2, Page 6 (https://arxiv.org/pdf/2306.10280.pdf) about Minesweeper had something wrong. The highest value is 89.70 ± 0.28 for Minesweeper, leading to a green color. 79.56 ± 1.09 shall be yellow, the baseline GCN for Minesweeper 78.28 ± 0.44 shall be blue color. BTW, nice work !

**Comment by zzysh12345** [comment]
Thanks for your correction! We will fix this error in the upcoming version of the paper.
