### ISSUE TITLE
DGL Dependency Question 

### ISSUE THREAD

**Issue by Bpoole908** [OpenGSL/OpenGSL#28]
Hi, I was just wondering why the repository is dependent both on PyG and DGL? More specifically why DGL is a dependency if PyG and DGL tend to do very similar things. I tried looking at the instances in code where DGL is used but since I'm relatively new to graph structure learning and graph neural networks so I've been having a hard time understanding how DGL is being used - even if it is sparingly imported. 

Any clarification on this point would be greatly appreciated as I survey various GSL repositories.

**Comment by zzysh12345** [comment]
Hello, thanks for pointing out the issue. Some methods use functions from DGL. We will address this issue by replacing those parts with PyG in future versions.
