### ISSUE TITLE
Considering supporting inductive dataset?

### ISSUE THREAD

**Issue by xmx-521** [OpenGSL/OpenGSL#29]
Hi, I'm wondering if the project is considering supporting inductive datasets, such as 20NewsGroups (used in many articles).

**Comment by zzysh12345** [comment]
Great advice! Most GSL works focus on transductive setting. A few of them(e.g., direct optimization methods) cannot be applied to the inductive setting. However, I think this is a topic worth researching. It's highly likely that we will incorporate inductive datasets in the future.

**Comment by xmx-521** [comment]
收到
