### ISSUE TITLE
Incorrect Indexing in gaug.py Leading to ValueError

### ISSUE THREAD

**Issue by KTTRCDL** [OpenGSL/OpenGSL#34]
## Description
First, thank you for your hard work on this project. I have encountered an issue in the file [gaug.py](vscode-file://vscode-app/c:/Users/mips/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) that leads to a ValueError due to incorrect indexing. Below is the relevant code excerpt:
```
def eval_edge_pred(adj_pred, val_edges, edge_labels):
    logits = adj_pred[val_edges.T]
    logits = np.nan_to_num(logits)
    roc_auc = roc_auc_score(edge_labels, logits)
    ap_score = average_precision_score(edge_labels, logits)
    return roc_auc, ap_score
```
Issue
The original code:
```
logits = adj_pred[val_edges.T]
```
should be modified to:
logits = adj_pred[val_edges.T[0], val_edges.T[1]]
## Reason
The original code causes an indexing error because [val_edges.T](vscode-file://vscode-app/c:/Users/mips/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) is a 2D array. Using it directly as an index results in a ValueError:
```
Exception has occurred: ValueError
Found array with dim 3. None expected <= 2.
line xxx, in eval_edge_pred
    roc_auc = roc_auc_score(edge_labels, logits)
ValueError: Found array with dim 3. None expected <= 2.
```
This error occurs because the incorrect indexing leads to an incorrect shape for [logits](vscode-file://vscode-app/c:/Users/mips/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html).
## Suggested Change
```
# modified, origin code: logits = adj_pred[val_edges.T] should be -> logits = adj_pred[val_edges.T[0], val_edges.T[1]]
logits = adj_pred[val_edges.T[0], val_edges.T[1]]
# logits = adj_pred[val_edges.T]
```
## Testing
Please ensure to run all relevant unit tests to verify the correctness of this change before merging.
## Please close this issue

**Comment by zzysh12345** [comment]
Thanks for your suggestion! I conducted tests and the current version is actually fine. This might be due to different versions of torch/numpy. Anyway, I will make the change you mentioned to avoid this error.
